/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andrealmeida' at '22/10/15 12:32' with Gradle 2.8
 *
 * @author andrealmeida, @date 22/10/15 12:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
