import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'andrealmeida' at '22/10/15 12:32' with Gradle 2.8
 *
 * @author andrealmeida, @date 22/10/15 12:32
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertFalse(classUnderTest.someLibraryMethod());
    }
}
